rewards = {
    'MOVED_LEFT': 0.04,
    'MOVED_RIGHT': 0.04,
    'MOVED_UP': 0.04,
    'MOVED_DOWN': 0.04,

    'WAITED': -0.04,
    'INTERRUPTED': 0,
    'INVALID_ACTION': -5,

    'BOMB_DROPPED': 0,
    'BOMB_EXPLODED': 0,

    'CRATE_DESTROYED': 30,
    'COIN_FOUND': 0,
    'COIN_COLLECTED':60,

    'KILLED_OPPONENT': 100,
    'KILLED_SELF': 0,

    'GOT_KILLED': -300,
    'OPPONENT_ELIMINATED': 0,
    'SURVIVED_ROUND':0,
}