rewards = {
    'MOVED_LEFT': 0,
    'MOVED_RIGHT': 0,
    'MOVED_UP': 0,
    'MOVED_DOWN': 0,

    'WAITED': -1,
    'INTERRUPTED': 0,
    'INVALID_ACTION': -5,

    'BOMB_DROPPED': 0,
    'BOMB_EXPLODED': 0,

    'CRATE_DESTROYED': 0,
    'COIN_FOUND': 0,
    'COIN_COLLECTED':5,

    'KILLED_OPPONENT': 0,
    'KILLED_SELF': 0,

    'GOT_KILLED': -5,
    'OPPONENT_ELIMINATED': 0,
    'SURVIVED_ROUND':0,
}